"""
Custom ToolAgentLoop with DB cleanup and stateful tool support.

Extends VERL's ToolAgentLoop to:
1. Use stable instance_id (request_id) for stateful tools across entire trajectory
2. Treat submit_solution as a "stop tool" that terminates the agent loop
3. Release database connections when ANY trajectory ends (not after each tool call)
4. Enforce trajectory timeout to prevent DBs being held forever

References:
- VERL stateful tool support: https://github.com/volcengine/verl/issues/2832
- VERL AI guidance: "Pass the same instance_id when calling tool.create() and
  subsequent tool.execute() calls to maintain state across turns"
"""
import asyncio
import gc
import json
import logging
import os
from typing import Any

from verl.experimental.agent_loop.tool_agent_loop import ToolAgentLoop, AgentState, AgentData, FunctionCall
from verl.experimental.agent_loop.agent_loop import AgentLoopOutput, AgentLoopMetrics
from verl.tools.schemas import ToolResponse
from verl.utils.rollout_trace import rollout_trace_op

logger = logging.getLogger(__name__)


class ToolAgentLoopWithDBCleanup(ToolAgentLoop):
    """
    ToolAgentLoop that supports stateful tools and ensures DB cleanup.

    Key features:
    1. Stateful tools: All tool calls in a trajectory share the same instance_id (request_id)
    2. Stop tool: submit_solution terminates the trajectory
    3. DB cleanup: Always released when trajectory ends (via try/finally in run())
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._current_request_id = None  # Track current trajectory's request_id

    @rollout_trace_op
    async def run(self, sampling_params: dict[str, Any], **kwargs) -> AgentLoopOutput:
        """
        Override run() to add DB cleanup and tool state cleanup in finally block.

        This ensures cleanup when trajectory ends, regardless of how:
        - submit_solution called (normal termination)
        - max turns reached
        - timeout (trajectory timeout enforced here)
        - error/exception
        """
        # Get trajectory timeout from environment (default 500s)
        # This prevents trajectories from holding DBs forever
        # NOTE: Ray actors may not inherit env vars from parent, so use 500s as default
        trajectory_timeout = float(os.environ.get("TRAJECTORY_TIMEOUT", "500"))

        # Debug: Log the timeout being used (helps diagnose env var issues)
        print(f"[TRAJECTORY TIMEOUT CONFIG] Using timeout={trajectory_timeout}s (env TRAJECTORY_TIMEOUT={os.environ.get('TRAJECTORY_TIMEOUT', 'NOT SET')})", flush=True)

        import time
        start_time = time.time()

        try:
            # Call parent run() with timeout to prevent holding DB forever
            return await asyncio.wait_for(
                super().run(sampling_params, **kwargs),
                timeout=trajectory_timeout
            )
        except asyncio.TimeoutError:
            elapsed = time.time() - start_time
            logger.error(f"[TRAJECTORY TIMEOUT] Trajectory exceeded {trajectory_timeout}s limit (actual: {elapsed:.1f}s), terminating")
            print(f"[TRAJECTORY TIMEOUT] Trajectory exceeded {trajectory_timeout}s limit (actual: {elapsed:.1f}s), terminating", flush=True)
            # Return valid output with pad token - the finally block will clean up DB
            # AgentLoopOutput requires: prompt_ids, response_ids, response_mask, metrics
            # Use pad_token_id (or 0) to create minimal valid output for tokenizer
            # NOTE: Don't use extra_fields here - it causes batch size mismatch when concatenating
            pad_token_id = getattr(self.tokenizer, 'pad_token_id', 0) or 0
            return AgentLoopOutput(
                prompt_ids=[pad_token_id],
                response_ids=[pad_token_id],
                response_mask=[0],  # 0 = not generated by LLM
                metrics=AgentLoopMetrics(),
                num_turns=0,
            )
        finally:
            # Log trajectory completion
            elapsed = time.time() - start_time
            print(f"[TRAJECTORY COMPLETE] Elapsed: {elapsed:.1f}s, timeout_limit: {trajectory_timeout}s", flush=True)

            # ALWAYS clean up when trajectory ends
            # Only release THIS trajectory's DB (identified by self._current_request_id)
            try:
                from bird_rl.tools.pool_manager import pool, instance_db_map

                instance_id = self._current_request_id

                # Only attempt cleanup if we have an instance_id
                # (trajectories without tool calls won't have one)
                if instance_id and instance_id in instance_db_map:
                    try:
                        # 1. Release DB back to pool
                        pooled_db = instance_db_map[instance_id]["pooled_db"]
                        print(f"[DB CLEANUP] Releasing DB {pooled_db.db_id}[{pooled_db.pool_index}] for instance {instance_id}", flush=True)
                        pool.release(pooled_db)
                        print(f"[DB CLEANUP] ✓ pool.release() completed successfully for {pooled_db.db_id}[{pooled_db.pool_index}]", flush=True)
                        del instance_db_map[instance_id]
                        logger.warning(f"[DB CLEANUP] Released DB for instance {instance_id}")
                        print(f"[DB CLEANUP] ✓ Released DB for instance {instance_id}", flush=True)

                        # 2. Clean up tool internal state (_instance_dict) to prevent memory leak
                        # Call release() on each tool that might have been used
                        for tool_name, tool in self.tools.items():
                            try:
                                await tool.release(instance_id)
                                logger.debug(f"[TOOL CLEANUP] Released {tool_name} state for instance {instance_id}")
                            except KeyError:
                                # Tool wasn't used in this trajectory, skip
                                pass
                            except Exception as e:
                                logger.warning(f"[TOOL CLEANUP] Error releasing {tool_name}: {e}")

                        print(f"[DB CLEANUP] ✓ Cleaned up trajectory {instance_id}", flush=True)
                    except Exception as e:
                        logger.error(f"[DB CLEANUP ERROR] Failed to release DB for {instance_id}: {e}")
                        print(f"[DB CLEANUP ERROR] Failed for {instance_id}: {e}", flush=True)
                elif instance_id:
                    # instance_id exists but not in map (already cleaned or never acquired)
                    logger.debug(f"[DB CLEANUP] No DB found for instance {instance_id} (already released or no tools called)")
                else:
                    # No instance_id (trajectory ended without calling any tools)
                    logger.debug("[DB CLEANUP] No instance_id - trajectory ended without tool calls")

            except Exception as e:
                logger.error(f"[DB CLEANUP ERROR] Failed during cleanup: {e}")
                print(f"[DB CLEANUP ERROR] {e}", flush=True)
            finally:
                # Reset for next trajectory
                self._current_request_id = None

    async def _call_tool(
        self, tool_call: FunctionCall, tools_kwargs: dict[str, Any], agent_data: AgentData
    ) -> tuple[ToolResponse, float, dict]:
        """
        Override to use stable instance_id for stateful tools.

        Key change from parent:
        - Pass instance_id=agent_data.request_id to tool.create()
        - This ensures all tool calls in trajectory share the same instance
        - Remove tool.release() from finally block (handled in run()'s finally)
        """
        tool, instance_id = None, None
        try:
            tool_name = tool_call.name
            tool_args = json.loads(tool_call.arguments)
            tool = self.tools[tool_name]
            kwargs = tools_kwargs.get(tool_name, {})

            # KEY FIX: Pass stable instance_id (request_id) for stateful tools
            instance_id, _ = await tool.create(
                instance_id=agent_data.request_id,  # ← Use stable ID for entire trajectory
                create_kwargs=kwargs.get("create_kwargs", {})
            )

            # Track this trajectory's request_id for cleanup
            self._current_request_id = agent_data.request_id

            tool_execution_response, tool_reward, res = await tool.execute(
                instance_id, tool_args, agent_data=agent_data
            )
        except Exception as e:
            logger.warning(f"Error when executing tool: {e}")
            return (
                ToolResponse(
                    text=f"Error when executing tool: {e}",
                ),
                0.0,
                {},
            )
        # NOTE: No finally block with tool.release() here!
        # DB cleanup happens in run()'s finally block when trajectory ends

        # Tool response processing (copied from parent)
        tool_response_text = tool_execution_response.text
        if tool_response_text and len(tool_response_text) > self.max_tool_response_length:
            if self.tool_response_truncate_side == "left":
                tool_response_text = tool_response_text[: self.max_tool_response_length] + "...(truncated)"
            elif self.tool_response_truncate_side == "right":
                tool_response_text = "(truncated)..." + tool_response_text[-self.max_tool_response_length :]
            else:
                length = self.max_tool_response_length // 2
                tool_response_text = tool_response_text[:length] + "...(truncated)..." + tool_response_text[-length:]

        # Create ToolResponse from tool execution result
        tool_response_kwargs = {"text": tool_response_text}
        if tool_execution_response.image:
            tool_response_kwargs["image"] = tool_execution_response.image
        if tool_execution_response.video:
            tool_response_kwargs["video"] = tool_execution_response.video

        return ToolResponse(**tool_response_kwargs), tool_reward, res

    async def _handle_processing_tools_state(self, agent_data: AgentData) -> AgentState:
        """
        Override to detect submit_solution and terminate the loop.

        This makes submit_solution act as a "stop tool" - when it's called,
        the trajectory ends. DB cleanup happens in run()'s finally block.
        """
        # Call parent to execute tools normally
        result_state = await super()._handle_processing_tools_state(agent_data)

        # Check if submit_solution was called
        for tool_call in agent_data.tool_calls[:self.max_parallel_calls]:
            if tool_call.name == "submit_solution":
                print(f"[STOP TOOL] submit_solution called, terminating trajectory", flush=True)
                logger.warning(f"[STOP TOOL] submit_solution called, terminating trajectory")
                return AgentState.TERMINATED

        return result_state
